### ISSUE TITLE
rift not loading

### ISSUE THREAD

**Issue by FeuerMongoid** [VolmitSoftware/Rift#4]
java.lang.NullPointerException: Cannot invoke "com.volmit.rift.RiftConfig.getDeleting()" because the return value of "com.volmit.rift.RiftConfig.get()" is null
        at com.volmit.rift.Rift.onEnable(Rift.java:29) ~[Rift.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:741) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:508) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:349) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by svdgoor** [comment]
you downgraded rift to an earlier version. delete the rift folder from plugins and try again.

**Comment by SwiftSwamp** [comment]
Closing as out dated, will be pushing update shortly for the rewrite, let us know if you still have issues / suggestions.
